version: '3.8'

services:
  # Django + Gunicorn
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spradar_web
    command: gunicorn --workers 4 --bind 0.0.0.0:8000 --timeout 300 --access-logfile /app/logs/gunicorn-access.log --error-logfile /app/logs/gunicorn-error.log spradar_api.wsgi:application
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env.docker
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=spradar_api.settings
    ports:
      - "8095:8000"
    restart: unless-stopped
    networks:
      - spradar_network

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: spradar_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - spradar_network

networks:
  spradar_network:
    driver: bridge
